// Code generated by eventgen, DO NOT EDIT.
package analytics_events

import (
	"github.com/example/events"
)
{{- range .Events }}{{- range . }}

type {{ title .Name }}V{{ .Version }} struct {
	events.EventBase `eventType:"{{ .Name }}"`
}
{{- end }}{{- end }}
