{{- define "columnTest" -}}
	{{- if .Nullable -}}
	if (evt.{{ title .Name }} == nil) != (expected{{ title .Name }} == nil) {
		return errors.Internal("nullable mismatch")
	}
	{{- else -}}
	if evt.{{ title .Name }} != expected{{ title .Name }} {
		return errors.Internal("value mismatch")
	}
	{{- end -}}
{{- end -}}

// Code generated by eventgen, DO NOT EDIT.
package analytics_events

import (
	"github.com/example/errors"
)
{{- range .Events }}

// Verify{{ .Name }}V{{ .Version }} checks one captured event.
func Verify{{ .Name }}V{{ .Version }}(evt *{{ .Name }}V{{ .Version }},
	{{- range .Columns }}
	expected{{ title .Name }} {{ .GoType }},
	{{- end }}
) error {
	{{- range .Columns }}
	{{ template "columnTest" . -}}
	{{- end }}
	return nil
}
{{ end }}
